import { existsSync, readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { basename, dirname, extname, resolve, sep as pathSeparator } from 'node:path';
import { chdir, cwd } from 'node:process';

import * as ejs from 'ejs';

import { globSync } from 'glob';

/**
 * Type only: the ESLint used to fix generated files is the one installed in the project the
 * CLI is running against, together with that project's own configuration. Importing it for
 * real would resolve this package's copy instead, and would force every installation of the
 * CLI to carry an ESLint of its own.
 */
import type * as ESLintModule from 'eslint';

import type { Project } from './project';
import type { PlannedFile } from './write-plan';


/* --------
 * Internal Types
 * -------- */
interface CompileOptions {
  /** A model passed down to compiler */
  model?: any;

  /** Disallow linting for the file */
  noLint?: boolean;

  /** Disable overriding file */
  noOverride?: boolean | ((fileName: string, path: string) => boolean);

  /** Print the disclaimer on top of produced output */
  printDisclaimer?: boolean;

  /** Rename the template when saving compiled file */
  rename?: string;
}

/** What the ESLint pass did, or the reason it could not run */
export interface LintOutcome {
  /** Files handed to ESLint */
  linted: number;

  /** Files ESLint actually rewrote */
  fixed: number;

  /** Set when the pass could not run at all */
  skipped?: string;

  /** Configuration problems ESLint reported per file, worded as ESLint worded them */
  problems: string[];
}


/* --------
 * Internal Constant
 * -------- */
const FIXABLE_EXTENSIONS: string[] = [ '.js', '.jsx', '.ts', '.tsx' ];

/**
 * Configuration file names, used **only** to locate the directory ESLint should run from.
 *
 * This is not a precondition: it used to gate the whole pass, so a project configured through
 * any name absent from the list — `.eslintrc.json`, `.eslintrc.yml`, `eslint.config.ts`, the
 * `eslintConfig` key of a package.json — was told it had no configuration and got no fix. The
 * list can only ever be incomplete, so when nothing matches the pass still runs and lets ESLint
 * itself decide whether it has something to work with.
 */
const ESLINT_CONFIGURATION_FILES: string[] = [
  'eslint.config.js',
  'eslint.config.mjs',
  'eslint.config.cjs',
  'eslint.config.ts',
  'eslint.config.mts',
  'eslint.config.cts',
  '.eslintrc.js',
  '.eslintrc.cjs',
  '.eslintrc.json',
  '.eslintrc.yaml',
  '.eslintrc.yml',
  '.eslintrc'
];


/* --------
 * Template Compiler Definition
 * -------- */
export class TemplateCompiler {

  /**
   * The template suffix to use while searching for templates
   * @private
   */
  private static readonly _templateSuffix: string = '.template.ejs';


  /**
   * Default disclaimer text to print above each compiled documents
   * @private
   */
  private static readonly _disclaimerText: string[] = [
    'This file is autogenerated by Proedis TemplatesCompiler utility.',
    'Does not modify this file as it could be overwritten'
  ];


  /**
   * A function that will return the disclaimer text, formatted
   * based on output document type
   * @private
   */
  public static getDisclaimer(): string {
    return [
      '/* --------',
      ' * AutoGenerated File',
      ' * --',
      ...this._disclaimerText.map((line) => ` * ${line}`),
      ' * -------- */'
    ].join('\n');
  }


  /**
   * Default compiler options to use while
   * saving templates
   * @private
   */
  private _defaultCompilerOptions: Partial<CompileOptions> = {};


  /**
   * Initialize a new TemplateCompiler setting the root
   * of the project to resolve files relative
   *
   * @param root The directory templates are resolved from
   * @param project The project being scaffolded
   */
  constructor(
    private readonly root: string,
    private readonly project: Project
  ) {

  }


  /**
   * Update the defaults compiler options for this instance
   * @param defaults
   */
  public defaults(defaults: Partial<CompileOptions>): this {
    this._defaultCompilerOptions = defaults;
    return this;
  }


  /**
   * Change the root path of the TemplateCompiler.
   * The path will be resolved starting from defined root.
   * This method will return a new TemplateCompiler
   * @param paths
   */
  public forPath(...paths: string[]): TemplateCompiler {
    return new TemplateCompiler(resolve(this.root, ...paths), this.project);
  }


  /**
   * Use the template suffix to build template name
   * for desired name
   * @param name
   */
  public getTemplateName(name: string): string {
    return `${name}${TemplateCompiler._templateSuffix}`;
  }


  /**
   * Get a template file in current root
   * @param name The template name, without the suffix
   */
  public getTemplate(name: string): string {
    const templateName = this.getTemplateName(name);
    const templatePath = resolve(this.root, templateName);

    if (!existsSync(templatePath)) {
      throw new Error(`No template named ${templateName} has been found in ${this.root} folder`);
    }

    return readFileSync(templatePath, 'utf-8');
  }


  /**
   * Return all templates in all directories
   */
  public getAllTemplates(): string[] {
    /** Search for all template files */
    return globSync(`**/*${TemplateCompiler._templateSuffix}`, {
      cwd          : this.root,
      dot          : true,
      nodir        : true,
      withFileTypes: false
    }).filter((t) => !basename(t).startsWith('_'));
  }


  /**
   * Compile a template file
   * @param name
   * @param options
   */
  public async compile(name: string, options?: CompileOptions): Promise<string> {
    /** Extract options */
    const {
      model,
      printDisclaimer
    } = {
      ...this._defaultCompilerOptions,
      ...options
    };

    /** Get the template from current root directory */
    const template = this.getTemplate(name);

    /** Render the template */
    return [
      printDisclaimer && `${TemplateCompiler.getDisclaimer()}\n\n`,
      ejs.render(template, model)
    ]
      .filter(Boolean)
      .join('')
      .replace(/(^\n)|(\n$)/gi, '');
  }


  /**
   * Render a template and return the file it would produce, without touching the disk.
   *
   * @param name The template name, without the suffix
   * @param path The directory the file belongs in
   * @param _options Compilation options
   * @return The planned file, or null when the template rendered to nothing meaningful
   */
  public async plan(name: string, path: string, _options?: CompileOptions): Promise<PlannedFile | null> {
    const options = {
      ...this._defaultCompilerOptions,
      ..._options
    };

    /** Get the file content compiling the requested template */
    const content = await this.compile(name, options);

    /** Set the file output name */
    const outputFilename = ejs.render(options.rename || name, options.model);
    const outputPath = resolve(path, outputFilename);

    return TemplateCompiler.toPlannedFile(outputPath, content, options.noOverride);
  }


  /**
   * Render every template below the current root, preserving the directory structure.
   *
   * @param root The directory the tree is written under
   * @param _options Compilation options
   * @return The planned files, in template order
   */
  public async planAll(
    root: string,
    _options?: Exclude<CompileOptions, 'rename'>
  ): Promise<PlannedFile[]> {
    const templates = this.getAllTemplates();

    if (!templates.length) {
      return [];
    }

    const options = {
      ...this._defaultCompilerOptions,
      ..._options
    };

    const templatesDescriptor = templates.map((template) => {
      const templateName = basename(template, TemplateCompiler._templateSuffix);
      const templatePath = dirname(template).replace(/^\./, '');

      return {
        name: templateName,
        path: templatePath ? templatePath.split(pathSeparator) : null
      };
    });

    /**
     * A plain async function, not 'new Promise(async …)': the Promise constructor discards its
     * executor's rejection, so a template that failed to compile left this promise pending and
     * hung the whole run on 'Promise.all' below, with no error to show for it.
     */
    const templatesPromises = templatesDescriptor.map(async (descriptor): Promise<PlannedFile | null> => {
      /** Create or use the current compiler */
      const compiler = descriptor.path ? this.forPath(...descriptor.path) : this;
      /** Compile the file */
      const content = await compiler.compile(descriptor.name, options);
      /** Create the output name */
      const outputName = ejs.render(descriptor.name, options.model);
      /** Create the output path */
      const outputPath = resolve(root, ...(descriptor.path || []), outputName);

      return TemplateCompiler.toPlannedFile(outputPath, content, options.noOverride);
    });

    return (await Promise.all(templatesPromises)).filter((file): file is PlannedFile => file !== null);
  }


  /**
   * Turn rendered content into a planned file, resolving whether it belongs to the user.
   *
   * @param path The absolute path the file belongs at
   * @param content The rendered content
   * @param noOverride The declaration, which may be a predicate over the file name
   * @return The planned file, or null when the content holds nothing worth writing
   */
  public static toPlannedFile(
    path: string,
    content: string,
    noOverride?: CompileOptions['noOverride']
  ): PlannedFile | null {
    /** A template that rendered to nothing but punctuation produces no file at all */
    if (!/[A-Za-z]/.test(content)) {
      return null;
    }

    const fileName = basename(path);

    return {
      content,
      noOverride: typeof noOverride === 'function' ? noOverride(fileName, path) : !!noOverride,
      path
    };
  }


  /**
   * Resolve the ESLint class from the project the CLI is running against, so generated
   * files are fixed with that project's own ESLint and rules.
   *
   * @return The ESLint class, or null when the project has no ESLint installed, which lets
   *         the caller degrade to a warning instead of failing the whole generation.
   */
  private resolveProjectEslint(): typeof ESLintModule.ESLint | null {
    try {
      const projectRequire = createRequire(resolve(this.project.rootDirectory, 'package.json'));
      return (projectRequire('eslint') as typeof ESLintModule).ESLint;
    }
    catch {
      return null;
    }
  }


  /**
   * The directory ESLint has to run from.
   *
   * This is not cosmetic. A relative `parserOptions.project` is resolved by
   * `@typescript-eslint/parser` against **the process working directory**, not against the `cwd`
   * handed to `new ESLint()` and not against the directory holding the configuration. In a
   * monorepo whose ESLint setup lives at the root — the shape of every project this scaffolder
   * actually runs in — invoking the CLI from inside a workspace made the parser look for
   * `<workspace>/tsconfig.eslint.json`, fail to read it, and report a fatal parsing error on
   * every generated file: the fix silently did nothing. Measured, and fixed by running the pass
   * from the configuration's own directory.
   *
   * @return The directory to run from, falling back to the project root when no known
   *         configuration file name is found — the pass still runs from there.
   */
  private resolveEslintWorkingDirectory(): string {
    const configurationPath = ESLINT_CONFIGURATION_FILES
      .map((fileName) => this.project.findFile(fileName))
      .find((path): path is string => path !== null);

    return configurationPath ? dirname(configurationPath) : this.project.rootDirectory;
  }


  /**
   * Fix the generated files with the ESLint installed in the target project.
   *
   * @param paths The files to fix, as returned by the write phase
   * @return What the pass did, so the caller can report it instead of guessing
   */
  public async lintAndFixFiles(paths: string[]): Promise<LintOutcome> {
    const outcome: LintOutcome = { linted: 0, fixed: 0, problems: [] };

    /** Filter keeping only the files ESLint has rules for */
    const fixablePaths = paths.filter((path) => FIXABLE_EXTENSIONS.includes(extname(path)));

    /** Assert at least one file exist */
    if (!fixablePaths.length) {
      return outcome;
    }

    /**
     * Load the ESLint installed in the target project.
     * This replaces an 'areDependenciesInstalled' probe for 'eslint': resolving the module
     * is the check that actually matters, and it guarantees the generated files are fixed
     * by the same ESLint the project itself uses.
     */
    const ESLint = this.resolveProjectEslint();

    if (!ESLint) {
      outcome.skipped = 'eslint is not installed in this project';
      return outcome;
    }

    /**
     * There used to be two more preconditions here: one asserting 'eslint-config-proedis' was
     * installed, and one asserting a configuration file existed among five hardcoded names.
     * Both could only produce false negatives — the first resolved from this package's location
     * rather than the project's and demanded one specific shared config where any working setup
     * will do, the second declared a correctly configured project unconfigured whenever it used
     * a name outside that list. Whether there is something to lint with is ESLint's answer to
     * give, and both of its ways of saying no are handled below.
     */
    const isLegacyEslint = Number.parseInt(ESLint.version ?? '', 10) < 9;

    const workingDirectory = this.resolveEslintWorkingDirectory();

    const eslint = new ESLint({
      cwd: workingDirectory,
      fix: true,
      /** Removed in ESLint 9, where passing it throws 'Invalid Options' */
      ...(isLegacyEslint ? { useEslintrc: true } : {})
    });

    /**
     * Run from the configuration's directory, then restore: see
     * 'resolveEslintWorkingDirectory' for why the process working directory is what decides
     * whether a relative 'parserOptions.project' resolves.
     */
    const callerWorkingDirectory = cwd();
    let results: ESLintModule.ESLint.LintResult[];

    try {
      chdir(workingDirectory);
      results = await eslint.lintFiles(fixablePaths);
    }
    catch (error) {
      /** An unloadable parser or an invalid flat config rejects here */
      outcome.skipped = (error as Error).message;
      return outcome;
    }
    finally {
      chdir(callerWorkingDirectory);
    }

    /**
     * Not every configuration problem rejects: an unreadable 'parserOptions.project' comes
     * back as a fatal parsing error on each result instead, so the results have to be
     * inspected as well. ESLint names the offending file, which is more useful than any
     * hint hardcoded here.
     */
    outcome.problems = [
      ...new Set(
        results
          .flatMap((result) => result.messages)
          .filter((message) => message.fatal)
          .map((message) => message.message)
      )
    ];

    /** Produce the fixing, for whichever files could be parsed */
    await ESLint.outputFixes(results);

    outcome.linted = results.length;
    outcome.fixed = results.filter((result) => result.output !== undefined).length;

    return outcome;
  }

}
